### ISSUE TITLE
Meaningful logs

### ISSUE THREAD

**Issue by EgorBu** [src-d/lookout-sdk-ml#71]
We need to improve logging in case of `Analyzer` doesn't have some required fields.
Example:
```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/event_listener.py", line 184, in wrapped_catch_them_all
    return func(self, request, context)
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/event_listener.py", line 209, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/usr/local/lib/python3.5/dist-packages/lookout/core/manager.py", line 98, in process_push_event
    mycfg = self._protobuf_struct_to_dict(request.configuration[analyzer.name])
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/well_known_types.py", line 741, in __getitem__
    return _GetStructValue(self.fields[key])
TypeError: None has type NoneType, but expected one of: bytes, unicode
```
and it happens when `Analyzer` doesn't have fields `model_type`, `name`.

**Comment by vmarkovtsev** [comment]
Fixed by https://github.com/src-d/lookout-sdk-ml/commit/e79ca46965ae63acd4df73611ca24eb815d89277
